### ISSUE TITLE
Incompatibility with Modern Industrialization ores

### ISSUE THREAD

**Issue by haleyjd** [Draylar/miners-horizon#18] opened 2021-04-18 09:56 UTC
Even if Modern Industrialization's ore generation is enabled and the ores are properly added to the Miner's Horizon configuration, they will not generate in the mining dimension. Instead, empty air blocks will appear throughout the stone where they appear to have attempted to generate. I am unsure which mod is responsible, and there are no errors or warnings in the Minecraft log to indicate what's happening. Being a programmer myself I took a look at both the mods' source codes but I don't know enough about it to tell what the issue might be.

MI generates its ores [here](https://github.com/AztechMC/Modern-Industrialization/blob/fd57752efe26422d7206ea1aa85513553ee73a69/src/main/java/aztech/modern_industrialization/materials/MIMaterials.java#L200) (in particular nickel, which is what I was mainly after). The OreMaterialPart.of() call seems to add its own definition for the ore.

**Comment by Wdavery** [comment] 2021-06-11 11:09
I seem to be having this same issue with Applied Energistics 2, though not consistently. I've had in generate properly in one world, and as air in another. 
Going to test further and will report back

**Comment by Wdavery** [comment] 2021-06-11 12:19
With Applied Energistics native ore gen turned on in it's config, Certus Quartz only generate at very deep levels and do not respect the miner's horizon config file. The config defined blocks seem to generate as air. 

With AE2's native ore gen turned off, no Certus Quartz generates at all, and there are still air blocks for what Miners Horizon
 is trying to generate.

EDIT: These results are the same even with the only mods installed being Fabric API, AE2 and Miners Horizon. Definitely not a mod conflict causing this. Something direct between AE2/Modern Industrialization and Miners Horizon

**Comment by Wdavery** [comment] 2021-06-11 12:45
Update: So turns out I didn't notice the config file had a typo  `appliedenergistics:quartz_ore` instead of `appliedenergistics2:quartz_ore` and now everything is working as expected.
@haleyjd  I'd triple check you config to make sure the ore is labelled properly because the air generating seems to be caused by Miners Horizon not finding the ore as listed.

Sorry for the spam here!

**Comment by dandin87** [comment] 2021-10-15 09:21
Hey Draylar, we are having the same issue in All of Fabric 4. Here is some info from Technician that could help fix it.

Trent87: So if I comment on this, What would I say exactly? That its skipping MI ores because of mod load order?
Technici4n: Yes
Technici4n: Moving to dedicated client and server initializers would fix this, except for AE2 which uses dedicated entrypoints
Technici4n: So... registry events
Technici4n: In this case it might be easier to just load ores lazily
Technici4n: I assume miners horizon has a custom chunk generator so... it's possible

**Comment by Draylar** [comment] 2021-10-18 18:08
Thanks for the information relay - I'm going to switch over to using the `Registry.BLOCK` event to register ore features as other mods register their content. This should prevent air blocks (which are caused by Miner's Horizon checking the registry for IDs that have not been registered yet, as Technici4n said). I have done some minimal testing for this with Modern Industrialization, but please let me know if you encounter the issue again in the future.

![image](https://user-images.githubusercontent.com/17728338/137783972-65e5d285-d888-46e2-9db6-9e1577c6c3b3.png)

Will be out in the next release!

**Closed by Draylar** 2021-10-18 18:08 UTC

**Comment by dandin87** [comment] 2021-10-19 05:18
This still appears to be an issue... Tried with All of Fabric 4, and then again with just MI and Miners Horizon. No MI ores are generating....
    {
      "block": "modern_industrialization:lead_ore",
      "size": 9,
      "count": 30,
      "minY": 100,
      "maxY": 255
    },
